spring.application.name=Practice7-11
DB_DRIVER=org.postgresql.Driver
DB_URL=jdbc:postgresql://localhost:5432/practice711
DB_USERNAME=sergey
DB_PASSWORD=1234

JPA_SHOW_SQL=true
HIBERNATE_DDL_AUTO=validate
HIBERNATE_FORMAT_SQL=true